#include <stdio.h>
#include <stdbool.h>

#define goal 500
/********************************************************************************
*																				*
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*
*																				*
********************************************************************************/
int triangle(int number)
{
	int triangle = 0;
	for (int i = 0; i <= number; i ++)
		triangle = triangle + i;
		

	printf("triangle # %d\n  total = %d\n", number, triangle );
	return triangle;
}

bool inarray(int array[], int length, int number)
{
	for (int i = 0; i < length; i++)
	{
		if (array[i] == number)
		{
			return true;
		}
	}
	return false;
}

int divisors(int number)
{
	int counter = 1;
	int divisors[1000];
	int j = 0;
	int calculator = number;
	for (int i = 0; i <= number / 2; i++)
		if (number % (i+1) == 0)
		{
			divisors[j] = i + 1; 
			j++;
			divisors[j] = calculator;
			j++;
			//printf("%d: %d / %d = %d\n", i + 1, calculator, i + 1, calculator / (i + 1));
			calculator = calculator / (i + 1);
			counter++;
		}

	//products of divisors
	for (int i = 0; i < j; i++)
	{
		for(int k = i + 1; k < j; k++)
		{
			if (divisors[i] > 1)
			{
				int product = divisors[i] * divisors[k];
				if ((product < number) && !(inarray(divisors, j, product)) && (number % product == 0))
					{
						divisors[j] = product;
						j++;
						printf("%d: %d * %d = %d\n", product, divisors[i], divisors[k], product);
						counter++;
					}
			}
		}
	}	
	printf("%d\n  number of divisors = %d\n", number, counter);

	return counter;
}

int main (void)
{
	int counter = 0;
	int trinum = 1;
	int counthi = 0;
	int answer = 1;

	while (counter < goal)
	{
		answer = triangle(trinum);
		counter = divisors(answer);
		trinum++;
		if (counter > counthi)
		{
			counthi = counter;
		}
		printf("  highest divisor count = %d \n\n", counthi);
	}

printf("triangle # %d\n", trinum);
printf("\nfinal answer == %d\n", answer);
}


